# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: c:/Users/M38172/Downloads/12022023/ngc/vc707_pcie_ep/Vivado/vc707_pcie_ep/vc707_pcie_ep_ex/imports/xilinx_pcie_7x_ep_x4g2_VC707.xdc

# IP: ip/vc707_pcie_ep/vc707_pcie_ep.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vc707_pcie_ep || ORIG_REF_NAME==vc707_pcie_ep} -quiet] -quiet
