# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Tony/Downloads/PCIe/12022023/tony/vc709_fmc_ep/Vivado/vc709_fmc_ep/vc709_fmc_ep.srcs/sources_1/ip/vc709_fmc_ep/vc709_fmc_ep.xci
# IP: The module: 'vc709_fmc_ep' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Tony/Downloads/PCIe/12022023/tony/vc709_fmc_ep/Vivado/vc709_fmc_ep/vc709_fmc_ep.gen/sources_1/ip/vc709_fmc_ep/source/vc709_fmc_ep-PCIE_X0Y1.xdc
# XDC: The top module name and the constraint reference have the same name: 'vc709_fmc_ep'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Tony/Downloads/PCIe/12022023/tony/vc709_fmc_ep/Vivado/vc709_fmc_ep/vc709_fmc_ep.gen/sources_1/ip/vc709_fmc_ep/synth/vc709_fmc_ep_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vc709_fmc_ep'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/Tony/Downloads/PCIe/12022023/tony/vc709_fmc_ep/Vivado/vc709_fmc_ep/vc709_fmc_ep.srcs/sources_1/ip/vc709_fmc_ep/vc709_fmc_ep.xci
# IP: The module: 'vc709_fmc_ep' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Tony/Downloads/PCIe/12022023/tony/vc709_fmc_ep/Vivado/vc709_fmc_ep/vc709_fmc_ep.gen/sources_1/ip/vc709_fmc_ep/source/vc709_fmc_ep-PCIE_X0Y1.xdc
# XDC: The top module name and the constraint reference have the same name: 'vc709_fmc_ep'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Tony/Downloads/PCIe/12022023/tony/vc709_fmc_ep/Vivado/vc709_fmc_ep/vc709_fmc_ep.gen/sources_1/ip/vc709_fmc_ep/synth/vc709_fmc_ep_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vc709_fmc_ep'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
