# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: vc707_hpc1.xdc

# Block Designs: bd/fpgadrv/fpgadrv.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpgadrv || ORIG_REF_NAME==fpgadrv} -quiet] -quiet

# IP: bd/fpgadrv/ip/fpgadrv_mig_0_0/fpgadrv_mig_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpgadrv_mig_0_0 || ORIG_REF_NAME==fpgadrv_mig_0_0} -quiet] -quiet

# IP: bd/fpgadrv/ip/fpgadrv_microblaze_0_0/fpgadrv_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpgadrv_microblaze_0_0 || ORIG_REF_NAME==fpgadrv_microblaze_0_0} -quiet] -quiet

# IP: bd/fpgadrv/ip/fpgadrv_dlmb_v10_0/fpgadrv_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpgadrv_dlmb_v10_0 || ORIG_REF_NAME==fpgadrv_dlmb_v10_0} -quiet] -quiet

# IP: bd/fpgadrv/ip/fpgadrv_ilmb_v10_0/fpgadrv_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpgadrv_ilmb_v10_0 || ORIG_REF_NAME==fpgadrv_ilmb_v10_0} -quiet] -quiet

# IP: bd/fpgadrv/ip/fpgadrv_dlmb_bram_if_cntlr_0/fpgadrv_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpgadrv_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==fpgadrv_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/fpgadrv/ip/fpgadrv_ilmb_bram_if_cntlr_0/fpgadrv_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpgadrv_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==fpgadrv_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/fpgadrv/ip/fpgadrv_lmb_bram_0/fpgadrv_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpgadrv_lmb_bram_0 || ORIG_REF_NAME==fpgadrv_lmb_bram_0} -quiet] -quiet

# IP: bd/fpgadrv/ip/fpgadrv_xbar_0/fpgadrv_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpgadrv_xbar_0 || ORIG_REF_NAME==fpgadrv_xbar_0} -quiet] -quiet

# IP: bd/fpgadrv/ip/fpgadrv_auto_us_1/fpgadrv_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpgadrv_auto_us_1 || ORIG_REF_NAME==fpgadrv_auto_us_1} -quiet] -quiet

# IP: bd/fpgadrv/ip/fpgadrv_auto_ds_0/fpgadrv_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpgadrv_auto_ds_0 || ORIG_REF_NAME==fpgadrv_auto_ds_0} -quiet] -quiet

# IP: bd/fpgadrv/ip/fpgadrv_auto_pc_0/fpgadrv_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpgadrv_auto_pc_0 || ORIG_REF_NAME==fpgadrv_auto_pc_0} -quiet] -quiet

# IP: bd/fpgadrv/ip/fpgadrv_auto_us_0/fpgadrv_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpgadrv_auto_us_0 || ORIG_REF_NAME==fpgadrv_auto_us_0} -quiet] -quiet

# IP: bd/fpgadrv/ip/fpgadrv_auto_cc_0/fpgadrv_auto_cc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpgadrv_auto_cc_0 || ORIG_REF_NAME==fpgadrv_auto_cc_0} -quiet] -quiet

# IP: bd/fpgadrv/ip/fpgadrv_auto_cc_1/fpgadrv_auto_cc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpgadrv_auto_cc_1 || ORIG_REF_NAME==fpgadrv_auto_cc_1} -quiet] -quiet

# IP: bd/fpgadrv/ip/fpgadrv_auto_ds_1/fpgadrv_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpgadrv_auto_ds_1 || ORIG_REF_NAME==fpgadrv_auto_ds_1} -quiet] -quiet

# IP: bd/fpgadrv/ip/fpgadrv_auto_ds_2/fpgadrv_auto_ds_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpgadrv_auto_ds_2 || ORIG_REF_NAME==fpgadrv_auto_ds_2} -quiet] -quiet

# IP: bd/fpgadrv/ip/fpgadrv_auto_ds_3/fpgadrv_auto_ds_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpgadrv_auto_ds_3 || ORIG_REF_NAME==fpgadrv_auto_ds_3} -quiet] -quiet

# IP: bd/fpgadrv/ip/fpgadrv_auto_ds_4/fpgadrv_auto_ds_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpgadrv_auto_ds_4 || ORIG_REF_NAME==fpgadrv_auto_ds_4} -quiet] -quiet

# IP: bd/fpgadrv/ip/fpgadrv_auto_ds_5/fpgadrv_auto_ds_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpgadrv_auto_ds_5 || ORIG_REF_NAME==fpgadrv_auto_ds_5} -quiet] -quiet

# IP: bd/fpgadrv/ip/fpgadrv_auto_ds_6/fpgadrv_auto_ds_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpgadrv_auto_ds_6 || ORIG_REF_NAME==fpgadrv_auto_ds_6} -quiet] -quiet

# IP: bd/fpgadrv/ip/fpgadrv_auto_pc_1/fpgadrv_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpgadrv_auto_pc_1 || ORIG_REF_NAME==fpgadrv_auto_pc_1} -quiet] -quiet

# IP: bd/fpgadrv/ip/fpgadrv_microblaze_0_axi_periph_0/fpgadrv_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpgadrv_microblaze_0_axi_periph_0 || ORIG_REF_NAME==fpgadrv_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/fpgadrv/ip/fpgadrv_microblaze_0_axi_intc_0/fpgadrv_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpgadrv_microblaze_0_axi_intc_0 || ORIG_REF_NAME==fpgadrv_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/fpgadrv/ip/fpgadrv_microblaze_0_xlconcat_0/fpgadrv_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpgadrv_microblaze_0_xlconcat_0 || ORIG_REF_NAME==fpgadrv_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/fpgadrv/ip/fpgadrv_mdm_1_0/fpgadrv_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpgadrv_mdm_1_0 || ORIG_REF_NAME==fpgadrv_mdm_1_0} -quiet] -quiet

# IP: bd/fpgadrv/ip/fpgadrv_rst_mig_0_100M_0/fpgadrv_rst_mig_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpgadrv_rst_mig_0_100M_0 || ORIG_REF_NAME==fpgadrv_rst_mig_0_100M_0} -quiet] -quiet

# IP: bd/fpgadrv/ip/fpgadrv_axi_smc_0/fpgadrv_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpgadrv_axi_smc_0 || ORIG_REF_NAME==fpgadrv_axi_smc_0} -quiet] -quiet

# IP: bd/fpgadrv/ip/fpgadrv_rst_mig_0_200M_0/fpgadrv_rst_mig_0_200M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpgadrv_rst_mig_0_200M_0 || ORIG_REF_NAME==fpgadrv_rst_mig_0_200M_0} -quiet] -quiet

# IP: bd/fpgadrv/ip/fpgadrv_reset_invert_0/fpgadrv_reset_invert_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpgadrv_reset_invert_0 || ORIG_REF_NAME==fpgadrv_reset_invert_0} -quiet] -quiet

# IP: bd/fpgadrv/ip/fpgadrv_axi_pcie_0_0/fpgadrv_axi_pcie_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpgadrv_axi_pcie_0_0 || ORIG_REF_NAME==fpgadrv_axi_pcie_0_0} -quiet] -quiet

# IP: bd/fpgadrv/ip/fpgadrv_rst_axi_pcie_0_125M_0/fpgadrv_rst_axi_pcie_0_125M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpgadrv_rst_axi_pcie_0_125M_0 || ORIG_REF_NAME==fpgadrv_rst_axi_pcie_0_125M_0} -quiet] -quiet

# IP: bd/fpgadrv/ip/fpgadrv_ref_clk_buf_0_0/fpgadrv_ref_clk_buf_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpgadrv_ref_clk_buf_0_0 || ORIG_REF_NAME==fpgadrv_ref_clk_buf_0_0} -quiet] -quiet

# IP: bd/fpgadrv/ip/fpgadrv_rst_pcie_axi_ctl_aclk_0_0/fpgadrv_rst_pcie_axi_ctl_aclk_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpgadrv_rst_pcie_axi_ctl_aclk_0_0 || ORIG_REF_NAME==fpgadrv_rst_pcie_axi_ctl_aclk_0_0} -quiet] -quiet

# IP: bd/fpgadrv/ip/fpgadrv_axi_uart16550_0_0/fpgadrv_axi_uart16550_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpgadrv_axi_uart16550_0_0 || ORIG_REF_NAME==fpgadrv_axi_uart16550_0_0} -quiet] -quiet

# IP: bd/fpgadrv/ip/fpgadrv_axi_timer_0_0/fpgadrv_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpgadrv_axi_timer_0_0 || ORIG_REF_NAME==fpgadrv_axi_timer_0_0} -quiet] -quiet

# IP: bd/fpgadrv/ip/fpgadrv_iic_main_0/fpgadrv_iic_main_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpgadrv_iic_main_0 || ORIG_REF_NAME==fpgadrv_iic_main_0} -quiet] -quiet

# IP: bd/fpgadrv/ip/fpgadrv_reset_gpio_0/fpgadrv_reset_gpio_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpgadrv_reset_gpio_0 || ORIG_REF_NAME==fpgadrv_reset_gpio_0} -quiet] -quiet

# IP: bd/fpgadrv/ip/fpgadrv_axi_emc_0_0/fpgadrv_axi_emc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpgadrv_axi_emc_0_0 || ORIG_REF_NAME==fpgadrv_axi_emc_0_0} -quiet] -quiet

# XDC: d:/Tony/Downloads/PCIe/fpga-drive-aximm-pcie/fmc--pcie/vc707/4_vc707_pcie_rc/Vivado/vc707_hpc1/vc707_hpc1.gen/sources_1/bd/fpgadrv/fpgadrv_ooc.xdc
