
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2022.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2024 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xaxipcie.h"

/*
* The configuration table for devices
*/

XAxiPcie_Config XAxiPcie_ConfigTable[XPAR_XAXIPCIE_NUM_INSTANCES] =
{
	{
		XPAR_AXI_PCIE_0_DEVICE_ID,
		XPAR_AXI_PCIE_0_BASEADDR,
		XPAR_AXI_PCIE_0_AXIBAR_NUM,
		XPAR_AXI_PCIE_0_INCLUDE_BAROFFSET_REG,
		XPAR_AXI_PCIE_0_INCLUDE_RC
	}
};


