# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/Tony/Downloads/PCIe/fpga-drive-aximm-pcie/fmc--pcie/vc709/4_vc709_fmc_ep/Vivado/vc709_fmc_ep/vc709_fmc_ep_ex/imports/xilinx_pcie3_7x_ep_x4g2_VC709.xdc

# IP: ip/vc709_fmc_ep/vc709_fmc_ep.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vc709_fmc_ep || ORIG_REF_NAME==vc709_fmc_ep} -quiet] -quiet
