# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "d:/Tony/Downloads/PCIe/12022023/vc709_pcie_ep/vc709_pcie_ep_ex/vc709_pcie_ep_ex.runs/synth_1/xilinx_pcie_3_0_7vx_ep.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7vx690tffg1761-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir d:/Tony/Downloads/PCIe/12022023/vc709_pcie_ep/vc709_pcie_ep_ex/vc709_pcie_ep_ex.cache/wt [current_project]
set_property parent.project_path d:/Tony/Downloads/PCIe/12022023/vc709_pcie_ep/vc709_pcie_ep_ex/vc709_pcie_ep_ex.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part xilinx.com:vc709:part0:1.8 [current_project]
set_property ip_output_repo d:/Tony/Downloads/PCIe/12022023/vc709_pcie_ep/vc709_pcie_ep_ex/vc709_pcie_ep_ex.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib {
  d:/Tony/Downloads/PCIe/12022023/vc709_pcie_ep/vc709_pcie_ep_ex/imports/EP_MEM.v
  d:/Tony/Downloads/PCIe/12022023/vc709_pcie_ep/vc709_pcie_ep_ex/imports/PIO.v
  d:/Tony/Downloads/PCIe/12022023/vc709_pcie_ep/vc709_pcie_ep_ex/imports/PIO_EP.v
  d:/Tony/Downloads/PCIe/12022023/vc709_pcie_ep/vc709_pcie_ep_ex/imports/PIO_EP_MEM_ACCESS.v
  d:/Tony/Downloads/PCIe/12022023/vc709_pcie_ep/vc709_pcie_ep_ex/imports/PIO_INTR_CTRL.v
  d:/Tony/Downloads/PCIe/12022023/vc709_pcie_ep/vc709_pcie_ep_ex/imports/PIO_RX_ENGINE.v
  d:/Tony/Downloads/PCIe/12022023/vc709_pcie_ep/vc709_pcie_ep_ex/imports/PIO_TO_CTRL.v
  d:/Tony/Downloads/PCIe/12022023/vc709_pcie_ep/vc709_pcie_ep_ex/imports/PIO_TX_ENGINE.v
  d:/Tony/Downloads/PCIe/12022023/vc709_pcie_ep/vc709_pcie_ep_ex/imports/pcie_app_7vx.v
  d:/Tony/Downloads/PCIe/12022023/vc709_pcie_ep/vc709_pcie_ep_ex/imports/vc709_pcie_ep_pipe_clock.v
  d:/Tony/Downloads/PCIe/12022023/vc709_pcie_ep/vc709_pcie_ep_ex/imports/vc709_pcie_ep_support.v
  d:/Tony/Downloads/PCIe/12022023/vc709_pcie_ep/vc709_pcie_ep_ex/imports/xilinx_pcie_3_0_7vx_ep.v
}
read_ip -quiet d:/Tony/Downloads/PCIe/12022023/vc709_pcie_ep/vc709_pcie_ep_ex/vc709_pcie_ep_ex.srcs/sources_1/ip/vc709_pcie_ep/vc709_pcie_ep.xci
set_property used_in_implementation false [get_files -all d:/Tony/Downloads/PCIe/12022023/vc709_pcie_ep/vc709_pcie_ep_ex/vc709_pcie_ep_ex.gen/sources_1/ip/vc709_pcie_ep/source/vc709_pcie_ep-PCIE_X0Y1.xdc]
set_property used_in_implementation false [get_files -all d:/Tony/Downloads/PCIe/12022023/vc709_pcie_ep/vc709_pcie_ep_ex/vc709_pcie_ep_ex.gen/sources_1/ip/vc709_pcie_ep/synth/vc709_pcie_ep_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc d:/Tony/Downloads/PCIe/12022023/vc709_pcie_ep/vc709_pcie_ep_ex/imports/xilinx_pcie3_7x_ep_x4g2_VC709.xdc
set_property used_in_implementation false [get_files d:/Tony/Downloads/PCIe/12022023/vc709_pcie_ep/vc709_pcie_ep_ex/imports/xilinx_pcie3_7x_ep_x4g2_VC709.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top xilinx_pcie_3_0_7vx_ep -part xc7vx690tffg1761-2
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef xilinx_pcie_3_0_7vx_ep.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file xilinx_pcie_3_0_7vx_ep_utilization_synth.rpt -pb xilinx_pcie_3_0_7vx_ep_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
