# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/M38172/Downloads/PCIe/fpga-drive-aximm-pcie/Vivado/vc707_hpc1/vc707_hpc1.srcs/sources_1/bd/fpgadrv/ip/fpgadrv_auto_cc_0/fpgadrv_auto_cc_0.xci
# IP: The module: 'fpgadrv_auto_cc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/M38172/Downloads/PCIe/fpga-drive-aximm-pcie/Vivado/vc707_hpc1/vc707_hpc1.gen/sources_1/bd/fpgadrv/ip/fpgadrv_auto_cc_0/fpgadrv_auto_cc_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fpgadrv_auto_cc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/M38172/Downloads/PCIe/fpga-drive-aximm-pcie/Vivado/vc707_hpc1/vc707_hpc1.gen/sources_1/bd/fpgadrv/ip/fpgadrv_auto_cc_0/fpgadrv_auto_cc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fpgadrv_auto_cc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/M38172/Downloads/PCIe/fpga-drive-aximm-pcie/Vivado/vc707_hpc1/vc707_hpc1.srcs/sources_1/bd/fpgadrv/ip/fpgadrv_auto_cc_0/fpgadrv_auto_cc_0.xci
# IP: The module: 'fpgadrv_auto_cc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/M38172/Downloads/PCIe/fpga-drive-aximm-pcie/Vivado/vc707_hpc1/vc707_hpc1.gen/sources_1/bd/fpgadrv/ip/fpgadrv_auto_cc_0/fpgadrv_auto_cc_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fpgadrv_auto_cc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/M38172/Downloads/PCIe/fpga-drive-aximm-pcie/Vivado/vc707_hpc1/vc707_hpc1.gen/sources_1/bd/fpgadrv/ip/fpgadrv_auto_cc_0/fpgadrv_auto_cc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fpgadrv_auto_cc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
