set_property SRC_FILE_INFO {cfile:c:/Users/M38172/Downloads/12022023/ngc/vc707_pcie_ep/Vivado/vc707_pcie_ep/vc707_pcie_ep_ex/imports/xilinx_pcie_7x_ep_x4g2_VC707.xdc rfile:../../../imports/xilinx_pcie_7x_ep_x4g2_VC707.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AV35 [get_ports sys_rst_n]
set_property src_info {type:XDC file:1 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AM39 [get_ports led_0]
set_property src_info {type:XDC file:1 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AN39 [get_ports led_1]
set_property src_info {type:XDC file:1 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AR37 [get_ports led_2]
set_property src_info {type:XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AT37 [get_ports led_3]
set_property src_info {type:XDC file:1 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IBUFDS_GTE2_X1Y5 [get_cells refclk_ibuf]
