# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Tony/Downloads/PCIe/12022023/tony/vc709_fmc_rc/Vivado/vc709_hpc/vc709_hpc.srcs/sources_1/bd/fpgadrv/ip/fpgadrv_auto_ds_1/fpgadrv_auto_ds_1.xci
# IP: The module: 'fpgadrv_auto_ds_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Tony/Downloads/PCIe/12022023/tony/vc709_fmc_rc/Vivado/vc709_hpc/vc709_hpc.gen/sources_1/bd/fpgadrv/ip/fpgadrv_auto_ds_1/fpgadrv_auto_ds_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fpgadrv_auto_ds_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Tony/Downloads/PCIe/12022023/tony/vc709_fmc_rc/Vivado/vc709_hpc/vc709_hpc.gen/sources_1/bd/fpgadrv/ip/fpgadrv_auto_ds_1/fpgadrv_auto_ds_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fpgadrv_auto_ds_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/Tony/Downloads/PCIe/12022023/tony/vc709_fmc_rc/Vivado/vc709_hpc/vc709_hpc.srcs/sources_1/bd/fpgadrv/ip/fpgadrv_auto_ds_1/fpgadrv_auto_ds_1.xci
# IP: The module: 'fpgadrv_auto_ds_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Tony/Downloads/PCIe/12022023/tony/vc709_fmc_rc/Vivado/vc709_hpc/vc709_hpc.gen/sources_1/bd/fpgadrv/ip/fpgadrv_auto_ds_1/fpgadrv_auto_ds_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fpgadrv_auto_ds_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Tony/Downloads/PCIe/12022023/tony/vc709_fmc_rc/Vivado/vc709_hpc/vc709_hpc.gen/sources_1/bd/fpgadrv/ip/fpgadrv_auto_ds_1/fpgadrv_auto_ds_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fpgadrv_auto_ds_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
