# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/M38172/Downloads/12022023/ngc/vc707_pcie_ep/Vivado/vc707_pcie_ep/vc707_pcie_ep.srcs/sources_1/ip/vc707_pcie_ep/vc707_pcie_ep.xci
# IP: The module: 'vc707_pcie_ep' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/M38172/Downloads/12022023/ngc/vc707_pcie_ep/Vivado/vc707_pcie_ep/vc707_pcie_ep.gen/sources_1/ip/vc707_pcie_ep/source/vc707_pcie_ep-PCIE_X1Y0.xdc
# XDC: The top module name and the constraint reference have the same name: 'vc707_pcie_ep'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/M38172/Downloads/12022023/ngc/vc707_pcie_ep/Vivado/vc707_pcie_ep/vc707_pcie_ep.gen/sources_1/ip/vc707_pcie_ep/synth/vc707_pcie_ep_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vc707_pcie_ep'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/M38172/Downloads/12022023/ngc/vc707_pcie_ep/Vivado/vc707_pcie_ep/vc707_pcie_ep.srcs/sources_1/ip/vc707_pcie_ep/vc707_pcie_ep.xci
# IP: The module: 'vc707_pcie_ep' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/M38172/Downloads/12022023/ngc/vc707_pcie_ep/Vivado/vc707_pcie_ep/vc707_pcie_ep.gen/sources_1/ip/vc707_pcie_ep/source/vc707_pcie_ep-PCIE_X1Y0.xdc
# XDC: The top module name and the constraint reference have the same name: 'vc707_pcie_ep'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/M38172/Downloads/12022023/ngc/vc707_pcie_ep/Vivado/vc707_pcie_ep/vc707_pcie_ep.gen/sources_1/ip/vc707_pcie_ep/synth/vc707_pcie_ep_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vc707_pcie_ep'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
