set_property SRC_FILE_INFO {cfile:{D:/Tony/Downloads/PCIe/fpga-drive-aximm-pcie/fmc -- pcie/vc709/2_vc709_pcie_ep/Vivado/vc709_pcie_ep/vc709_pcie_ep_ex/imports/xilinx_pcie3_7x_ep_x4g2_VC709.xdc} rfile:../../../imports/xilinx_pcie3_7x_ep_x4g2_VC709.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AM39 [get_ports led_0]
set_property src_info {type:XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AN39 [get_ports led_1]
set_property src_info {type:XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AR37 [get_ports led_2]
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AT37 [get_ports led_3]
set_property src_info {type:XDC file:1 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AV35 [get_ports sys_rst_n]
set_property src_info {type:XDC file:1 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IBUFDS_GTE2_X1Y11 [get_cells refclk_ibuf]
