# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/Tony/Downloads/PCIe/fpga-drive-aximm-pcie/fmc -- pcie/vc709/2_vc709_pcie_ep/Vivado/vc709_pcie_ep/vc709_pcie_ep_ex/imports/xilinx_pcie3_7x_ep_x4g2_VC709.xdc

# IP: ip/vc709_pcie_ep/vc709_pcie_ep.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vc709_pcie_ep || ORIG_REF_NAME==vc709_pcie_ep} -quiet] -quiet
