# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Tony/Downloads/PCIe/12022023/tony/vc709_fmc_rc/Vivado/vc709_hpc/vc709_hpc.srcs/sources_1/bd/fpgadrv/ip/fpgadrv_axi_pcie_0_0/fpgadrv_axi_pcie_0_0.xci
# IP: The module: 'fpgadrv_axi_pcie_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/Tony/Downloads/PCIe/12022023/tony/vc709_fmc_rc/Vivado/vc709_hpc/vc709_hpc.gen/sources_1/bd/fpgadrv/ip/fpgadrv_axi_pcie_0_0/ip_2/fpgadrv_axi_pcie_0_0_pcie3_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpgadrv_axi_pcie_0_0_pcie3_ip || ORIG_REF_NAME==fpgadrv_axi_pcie_0_0_pcie3_ip} -quiet] -quiet

# IP: d:/Tony/Downloads/PCIe/12022023/tony/vc709_fmc_rc/Vivado/vc709_hpc/vc709_hpc.gen/sources_1/bd/fpgadrv/ip/fpgadrv_axi_pcie_0_0/ip_1/axi_pcie3_v3_0_22_fifo_generator_v13_1_4_64B_parity.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_pcie3_v3_0_22_fifo_generator_v13_1_4_64B_parity || ORIG_REF_NAME==axi_pcie3_v3_0_22_fifo_generator_v13_1_4_64B_parity} -quiet] -quiet

# IP: d:/Tony/Downloads/PCIe/12022023/tony/vc709_fmc_rc/Vivado/vc709_hpc/vc709_hpc.gen/sources_1/bd/fpgadrv/ip/fpgadrv_axi_pcie_0_0/ip_0/axi_pcie3_v3_0_22_blk_mem_gen_v8_3_6_64B_parity.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_pcie3_v3_0_22_blk_mem_gen_v8_3_6_64B_parity || ORIG_REF_NAME==axi_pcie3_v3_0_22_blk_mem_gen_v8_3_6_64B_parity} -quiet] -quiet

# XDC: d:/Tony/Downloads/PCIe/12022023/tony/vc709_fmc_rc/Vivado/vc709_hpc/vc709_hpc.gen/sources_1/bd/fpgadrv/ip/fpgadrv_axi_pcie_0_0/ip_2/source/fpgadrv_axi_pcie_0_0_pcie3_ip-PCIE_X0Y2.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fpgadrv_axi_pcie_0_0_pcie3_ip || ORIG_REF_NAME==fpgadrv_axi_pcie_0_0_pcie3_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/Tony/Downloads/PCIe/12022023/tony/vc709_fmc_rc/Vivado/vc709_hpc/vc709_hpc.gen/sources_1/bd/fpgadrv/ip/fpgadrv_axi_pcie_0_0/ip_2/synth/fpgadrv_axi_pcie_0_0_pcie3_ip_ooc.xdc

# XDC: d:/Tony/Downloads/PCIe/12022023/tony/vc709_fmc_rc/Vivado/vc709_hpc/vc709_hpc.gen/sources_1/bd/fpgadrv/ip/fpgadrv_axi_pcie_0_0/ip_1/axi_pcie3_v3_0_22_fifo_generator_v13_1_4_64B_parity.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_pcie3_v3_0_22_fifo_generator_v13_1_4_64B_parity || ORIG_REF_NAME==axi_pcie3_v3_0_22_fifo_generator_v13_1_4_64B_parity} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Tony/Downloads/PCIe/12022023/tony/vc709_fmc_rc/Vivado/vc709_hpc/vc709_hpc.gen/sources_1/bd/fpgadrv/ip/fpgadrv_axi_pcie_0_0/ip_0/axi_pcie3_v3_0_22_blk_mem_gen_v8_3_6_64B_parity_ooc.xdc

# XDC: d:/Tony/Downloads/PCIe/12022023/tony/vc709_fmc_rc/Vivado/vc709_hpc/vc709_hpc.gen/sources_1/bd/fpgadrv/ip/fpgadrv_axi_pcie_0_0/fpgadrv_axi_pcie_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'fpgadrv_axi_pcie_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Tony/Downloads/PCIe/12022023/tony/vc709_fmc_rc/Vivado/vc709_hpc/vc709_hpc.gen/sources_1/bd/fpgadrv/ip/fpgadrv_axi_pcie_0_0/source/fpgadrv_axi_pcie_0_0_apcie3_7vx_ip_xdc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fpgadrv_axi_pcie_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Tony/Downloads/PCIe/12022023/tony/vc709_fmc_rc/Vivado/vc709_hpc/vc709_hpc.gen/sources_1/bd/fpgadrv/ip/fpgadrv_axi_pcie_0_0/synth/fpgadrv_axi_pcie_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fpgadrv_axi_pcie_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/Tony/Downloads/PCIe/12022023/tony/vc709_fmc_rc/Vivado/vc709_hpc/vc709_hpc.srcs/sources_1/bd/fpgadrv/ip/fpgadrv_axi_pcie_0_0/fpgadrv_axi_pcie_0_0.xci
# IP: The module: 'fpgadrv_axi_pcie_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/Tony/Downloads/PCIe/12022023/tony/vc709_fmc_rc/Vivado/vc709_hpc/vc709_hpc.gen/sources_1/bd/fpgadrv/ip/fpgadrv_axi_pcie_0_0/ip_2/fpgadrv_axi_pcie_0_0_pcie3_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fpgadrv_axi_pcie_0_0_pcie3_ip || ORIG_REF_NAME==fpgadrv_axi_pcie_0_0_pcie3_ip} -quiet] -quiet

# IP: d:/Tony/Downloads/PCIe/12022023/tony/vc709_fmc_rc/Vivado/vc709_hpc/vc709_hpc.gen/sources_1/bd/fpgadrv/ip/fpgadrv_axi_pcie_0_0/ip_1/axi_pcie3_v3_0_22_fifo_generator_v13_1_4_64B_parity.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_pcie3_v3_0_22_fifo_generator_v13_1_4_64B_parity || ORIG_REF_NAME==axi_pcie3_v3_0_22_fifo_generator_v13_1_4_64B_parity} -quiet] -quiet

# IP: d:/Tony/Downloads/PCIe/12022023/tony/vc709_fmc_rc/Vivado/vc709_hpc/vc709_hpc.gen/sources_1/bd/fpgadrv/ip/fpgadrv_axi_pcie_0_0/ip_0/axi_pcie3_v3_0_22_blk_mem_gen_v8_3_6_64B_parity.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_pcie3_v3_0_22_blk_mem_gen_v8_3_6_64B_parity || ORIG_REF_NAME==axi_pcie3_v3_0_22_blk_mem_gen_v8_3_6_64B_parity} -quiet] -quiet

# XDC: d:/Tony/Downloads/PCIe/12022023/tony/vc709_fmc_rc/Vivado/vc709_hpc/vc709_hpc.gen/sources_1/bd/fpgadrv/ip/fpgadrv_axi_pcie_0_0/ip_2/source/fpgadrv_axi_pcie_0_0_pcie3_ip-PCIE_X0Y2.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fpgadrv_axi_pcie_0_0_pcie3_ip || ORIG_REF_NAME==fpgadrv_axi_pcie_0_0_pcie3_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/Tony/Downloads/PCIe/12022023/tony/vc709_fmc_rc/Vivado/vc709_hpc/vc709_hpc.gen/sources_1/bd/fpgadrv/ip/fpgadrv_axi_pcie_0_0/ip_2/synth/fpgadrv_axi_pcie_0_0_pcie3_ip_ooc.xdc

# XDC: d:/Tony/Downloads/PCIe/12022023/tony/vc709_fmc_rc/Vivado/vc709_hpc/vc709_hpc.gen/sources_1/bd/fpgadrv/ip/fpgadrv_axi_pcie_0_0/ip_1/axi_pcie3_v3_0_22_fifo_generator_v13_1_4_64B_parity.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_pcie3_v3_0_22_fifo_generator_v13_1_4_64B_parity || ORIG_REF_NAME==axi_pcie3_v3_0_22_fifo_generator_v13_1_4_64B_parity} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Tony/Downloads/PCIe/12022023/tony/vc709_fmc_rc/Vivado/vc709_hpc/vc709_hpc.gen/sources_1/bd/fpgadrv/ip/fpgadrv_axi_pcie_0_0/ip_0/axi_pcie3_v3_0_22_blk_mem_gen_v8_3_6_64B_parity_ooc.xdc

# XDC: d:/Tony/Downloads/PCIe/12022023/tony/vc709_fmc_rc/Vivado/vc709_hpc/vc709_hpc.gen/sources_1/bd/fpgadrv/ip/fpgadrv_axi_pcie_0_0/fpgadrv_axi_pcie_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'fpgadrv_axi_pcie_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Tony/Downloads/PCIe/12022023/tony/vc709_fmc_rc/Vivado/vc709_hpc/vc709_hpc.gen/sources_1/bd/fpgadrv/ip/fpgadrv_axi_pcie_0_0/source/fpgadrv_axi_pcie_0_0_apcie3_7vx_ip_xdc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fpgadrv_axi_pcie_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Tony/Downloads/PCIe/12022023/tony/vc709_fmc_rc/Vivado/vc709_hpc/vc709_hpc.gen/sources_1/bd/fpgadrv/ip/fpgadrv_axi_pcie_0_0/synth/fpgadrv_axi_pcie_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fpgadrv_axi_pcie_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
